# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e7bde59efe77dd48a4852e27cbb552ac713c17f6d6f78ec478ad1c8476d19385bc3b0f6fe0c2249fecdd0485e4852775de34b4a05bdadadda2241f8f06e610d

test:
  secret_key_base: 6b8b6bcc64b1244ffcf9190abc64113c601bfeb530e8f06a1e63157ab25537ede6ed2bcd8cbcf4e111d139bfd16da6febee1c5aa78acad4ab6e5e76eaee65dee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
